package com.upb.model;
// Generated 3 f�vr. 2023, 01:03:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Appartenir generated by hbm2java
 */
@Entity
@Table(name = "appartenir", catalog = "hotel")
public class Appartenir implements java.io.Serializable {

	private AppartenirId id;

	public Appartenir() {
	}

	public Appartenir(AppartenirId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idFormule", column = @Column(name = "ID_FORMULE", nullable = false)),
			@AttributeOverride(name = "idType", column = @Column(name = "ID_TYPE", nullable = false)),
			@AttributeOverride(name = "idChambre", column = @Column(name = "ID_CHAMBRE", nullable = false)) })
	public AppartenirId getId() {
		return this.id;
	}

	public void setId(AppartenirId id) {
		this.id = id;
	}

}
