package com.upb.model;
// Generated 3 f�vr. 2023, 01:03:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppartenirId generated by hbm2java
 */
@Embeddable
public class AppartenirId implements java.io.Serializable {

	private int idFormule;
	private int idType;
	private int idChambre;

	public AppartenirId() {
	}

	public AppartenirId(int idFormule, int idType, int idChambre) {
		this.idFormule = idFormule;
		this.idType = idType;
		this.idChambre = idChambre;
	}

	@Column(name = "ID_FORMULE", nullable = false)
	public int getIdFormule() {
		return this.idFormule;
	}

	public void setIdFormule(int idFormule) {
		this.idFormule = idFormule;
	}

	@Column(name = "ID_TYPE", nullable = false)
	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	@Column(name = "ID_CHAMBRE", nullable = false)
	public int getIdChambre() {
		return this.idChambre;
	}

	public void setIdChambre(int idChambre) {
		this.idChambre = idChambre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppartenirId))
			return false;
		AppartenirId castOther = (AppartenirId) other;

		return (this.getIdFormule() == castOther.getIdFormule()) && (this.getIdType() == castOther.getIdType())
				&& (this.getIdChambre() == castOther.getIdChambre());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFormule();
		result = 37 * result + this.getIdType();
		result = 37 * result + this.getIdChambre();
		return result;
	}

}
