package com.upb.model;
// Generated 3 f�vr. 2023, 01:03:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReservationId generated by hbm2java
 */
@Embeddable
public class ReservationId implements java.io.Serializable {

	private int idClient;
	private int idChambre;

	public ReservationId() {
	}

	public ReservationId(int idClient, int idChambre) {
		this.idClient = idClient;
		this.idChambre = idChambre;
	}

	@Column(name = "ID_CLIENT", nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Column(name = "ID_CHAMBRE", nullable = false)
	public int getIdChambre() {
		return this.idChambre;
	}

	public void setIdChambre(int idChambre) {
		this.idChambre = idChambre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservationId))
			return false;
		ReservationId castOther = (ReservationId) other;

		return (this.getIdClient() == castOther.getIdClient()) && (this.getIdChambre() == castOther.getIdChambre());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdClient();
		result = 37 * result + this.getIdChambre();
		return result;
	}

}
