package com.upb.model;
// Generated 3 f�vr. 2023, 01:03:37 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "hotel")
public class Reservation implements java.io.Serializable {

	private ReservationId id;
	private Integer idReservation;
	private Date dateDebut;
	private Date dateFin;

	public Reservation() {
	}

	public Reservation(ReservationId id) {
		this.id = id;
	}

	public Reservation(ReservationId id, Integer idReservation, Date dateDebut, Date dateFin) {
		this.id = id;
		this.idReservation = idReservation;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idClient", column = @Column(name = "ID_CLIENT", nullable = false)),
			@AttributeOverride(name = "idChambre", column = @Column(name = "ID_CHAMBRE", nullable = false)) })
	public ReservationId getId() {
		return this.id;
	}

	public void setId(ReservationId id) {
		this.id = id;
	}

	@Column(name = "ID_RESERVATION")
	public Integer getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(Integer idReservation) {
		this.idReservation = idReservation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
