package com.upb.model;
// Generated 3 f�vr. 2023, 01:03:37 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "hotel")
public class Type implements java.io.Serializable {

	private Integer idType;
	private String suite;
	private String standart;

	public Type() {
	}

	public Type(String suite, String standart) {
		this.suite = suite;
		this.standart = standart;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TYPE", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "SUITE", length = 10)
	public String getSuite() {
		return this.suite;
	}

	public void setSuite(String suite) {
		this.suite = suite;
	}

	@Column(name = "STANDART", length = 10)
	public String getStandart() {
		return this.standart;
	}

	public void setStandart(String standart) {
		this.standart = standart;
	}

}
